language: go

go:
  - 1.7.5
  - 1.8.5
  - 1.9.2
install:
  - go get github.com/astaxie/beego
  - go get github.com/astaxie/beego/cache
  - go get github.com/astaxie/beego/logs
  - go get github.com/mattn/go-sqlite3
  - go get github.com/twinj/uuid
  - go get github.com/axgle/mahonia
  - go get github.com/smartystreets/goconvey

#go_import_path: github.com/jicg/lyblog